services:
  paper:
    container_name: paper
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: paper:local
    expose:
      - "25570"
    volumes:
      - paper_world:/backend/world

  velocity:
    container_name: velocity
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: velocity:local
    depends_on:
      - paper
    ports:
      - "25565:25565"

volumes:
  paper_world:
